### ISSUE TITLE
[Chapter - Process Memory Access] Reading TEB of another process using the TEB address of current process

### ISSUE THREAD

**Issue by tuhdo** [ellysh/video-game-bots#1]
In [TebPebMirror.cpp](https://ellysh.gitbooks.io/video-game-bots/content/Examples/InGameBots/ProcessMemoryAccess/TebPebMirror.cpp), we assign it some PID of an application to get its TEB. However, `GetMainThreadTeb` function get the address of current process TEB with `NtCurrentTeb`, then use that address to read in another process, which is invalid in the other process. The only way it works properly is that I retrieve the current PID of the `TebPebMirror` program itself. 

I think it is a mistake, or maybe I am missing something else? Thanks for the awesome free book.

**Comment by ellysh** [comment]
You are right in the general case. But I have experimentally find that Windows in most cases assigns the same address for the TEB segment for 32-bit applications. Yes, this approach is not reliable. But it is quite easy to implement. I suppose that it will be good to start from such simple example.

**Comment by tuhdo** [comment]
Oh I see the idea. You should add this detail to the book.

**Comment by ellysh** [comment]
Fixed.
